import pandas as pd
# Raw Data
data = [
    {
        "Student": "Ali Khan",
        "Gender": "Male",
        "Subject": "Mathematics",
        "Marks": 52,
        "Attendance_%": 75.0,
        "Exam_Date": "2025-01-15 09:00:00",
    },
    {
        "Student": "Ahmed Raza",
        "Gender": "Male",
        "Subject": "Mathematics",
        "Marks": 55,
        "Attendance_%": 80.5,
        "Exam_Date": "2025-01-15 09:00:00",
    },
    {
        "Student": "Bilal Ahmed",
        "Gender": "Male",
        "Subject": "Physics",
        "Marks": 58,
        "Attendance_%": 78.0,
        "Exam_Date": "2025-01-16 11:30:00",
    },
    {
        "Student": "Usman Tariq",
        "Gender": "Male",
        "Subject": "Physics",
        "Marks": 61,
        "Attendance_%": 82.0,
        "Exam_Date": "2025-01-16 11:30:00",
    },
    {
        "Student": "Hamza Malik",
        "Gender": "Male",
        "Subject": "Chemistry",
        "Marks": 64,
        "Attendance_%": 85.0,
        "Exam_Date": "2025-01-18 10:00:00",
    },
    {
        "Student": "Sara Ali",
        "Gender": "Female",
        "Subject": "Mathematics",
        "Marks": 53,
        "Attendance_%": 70.0,
        "Exam_Date": "2025-01-15 09:00:00",
    },
    {
        "Student": "Ayesha Noor",
        "Gender": "Female",
        "Subject": "Mathematics",
        "Marks": 57,
        "Attendance_%": 76.5,
        "Exam_Date": "2025-01-15 09:00:00",
    },
    {
        "Student": "Fatima Khan",
        "Gender": "Female",
        "Subject": "Physics",
        "Marks": 62,
        "Attendance_%": 81.0,
        "Exam_Date": "2025-01-16 11:30:00",
    },
    {
        "Student": "Zainab Ahmed",
        "Gender": "Female",
        "Subject": "Physics",
        "Marks": 66,
        "Attendance_%": 88.0,
        "Exam_Date": "2025-01-16 11:30:00",
    },
    {
        "Student": "Hira Sheikh",
        "Gender": "Female",
        "Subject": "Chemistry",
        "Marks": 69,
        "Attendance_%": 90.0,
        "Exam_Date": "2025-01-18 10:00:00",
    },
    {
        "Student": "Daniyal Shah",
        "Gender": "Male",
        "Subject": "Mathematics",
        "Marks": 72,
        "Attendance_%": 84.0,
        "Exam_Date": "2025-01-15 09:00:00",
    },
    {
        "Student": "Saad Hussain",
        "Gender": "Male",
        "Subject": "Physics",
        "Marks": 76,
        "Attendance_%": 89.5,
        "Exam_Date": "2025-01-16 11:30:00",
    },
    {
        "Student": "Muneeb Ali",
        "Gender": "Male",
        "Subject": "Chemistry",
        "Marks": 81,
        "Attendance_%": 91.0,
        "Exam_Date": "2025-01-18 10:00:00",
    },
    {
        "Student": "Iqra Malik",
        "Gender": "Female",
        "Subject": "Mathematics",
        "Marks": 74,
        "Attendance_%": 86.0,
        "Exam_Date": "2025-01-15 09:00:00",
    },
    {
        "Student": "Maryam Noor",
        "Gender": "Female",
        "Subject": "Chemistry",
        "Marks": 88,
        "Attendance_%": 94.0,
        "Exam_Date": "2025-01-18 10:00:00",
    },
    {
        "Student": "Abdullah Khan",
        "Gender": "Male",
        "Subject": "Mathematics",
        "Marks": 91,
        "Attendance_%": 96.0,
        "Exam_Date": "2025-01-15 09:00:00",
    },
    {
        "Student": "Talha Ahmed",
        "Gender": "Male",
        "Subject": "Physics",
        "Marks": 93,
        "Attendance_%": 98.0,
        "Exam_Date": "2025-01-16 11:30:00",
    },
    {
        "Student": "Laiba Fatima",
        "Gender": "Female",
        "Subject": "Chemistry",
        "Marks": 95,
        "Attendance_%": 97.5,
        "Exam_Date": "2025-01-18 10:00:00",
    },
    {
        "Student": "Mahnoor Ali",
        "Gender": "Female",
        "Subject": "Physics",
        "Marks": 97,
        "Attendance_%": 99.0,
        "Exam_Date": "2025-01-16 11:30:00",
    },
    {
        "Student": "Eman Raza",
        "Gender": "Female",
        "Subject": "Chemistry",
        "Marks": 99,
        "Attendance_%": 100.0,
        "Exam_Date": "2025-01-18 10:00:00",
    },
    {
        "Student": "Ali Khan",
        "Gender": "Male",
        "Subject": "Computer Science",
        "Marks": 60,
        "Attendance_%": 78.0,
        "Exam_Date": "2025-03-10 14:00:00",
    },
    {
        "Student": "Ahmed Raza",
        "Gender": "Male",
        "Subject": "Computer Science",
        "Marks": 63,
        "Attendance_%": 82.0,
        "Exam_Date": "2025-03-10 14:00:00",
    },
    {
        "Student": "Bilal Ahmed",
        "Gender": "Male",
        "Subject": "Mathematics",
        "Marks": 65,
        "Attendance_%": 80.0,
        "Exam_Date": "2025-03-12 09:00:00",
    },
    {
        "Student": "Usman Tariq",
        "Gender": "Male",
        "Subject": "Mathematics",
        "Marks": 70,
        "Attendance_%": 84.0,
        "Exam_Date": "2025-03-12 09:00:00",
    },
    {
        "Student": "Hamza Malik",
        "Gender": "Male",
        "Subject": "Physics",
        "Marks": 68,
        "Attendance_%": 86.5,
        "Exam_Date": "2025-03-14 11:30:00",
    },
    {
        "Student": "Sara Ali",
        "Gender": "Female",
        "Subject": "Computer Science",
        "Marks": 58,
        "Attendance_%": 72.0,
        "Exam_Date": "2025-03-10 14:00:00",
    },
    {
        "Student": "Ayesha Noor",
        "Gender": "Female",
        "Subject": "Computer Science",
        "Marks": 62,
        "Attendance_%": 79.0,
        "Exam_Date": "2025-03-10 14:00:00",
    },
    {
        "Student": "Fatima Khan",
        "Gender": "Female",
        "Subject": "Mathematics",
        "Marks": 67,
        "Attendance_%": 83.0,
        "Exam_Date": "2025-03-12 09:00:00",
    },
    {
        "Student": "Zainab Ahmed",
        "Gender": "Female",
        "Subject": "Mathematics",
        "Marks": 71,
        "Attendance_%": 89.0,
        "Exam_Date": "2025-03-12 09:00:00",
    },
    {
        "Student": "Hira Sheikh",
        "Gender": "Female",
        "Subject": "Physics",
        "Marks": 73,
        "Attendance_%": 91.5,
        "Exam_Date": "2025-03-14 11:30:00",
    },
    {
        "Student": "Daniyal Shah",
        "Gender": "Male",
        "Subject": "Computer Science",
        "Marks": 78,
        "Attendance_%": 87.0,
        "Exam_Date": "2025-03-10 14:00:00",
    },
    {
        "Student": "Saad Hussain",
        "Gender": "Male",
        "Subject": "Mathematics",
        "Marks": 82,
        "Attendance_%": 91.0,
        "Exam_Date": "2025-03-12 09:00:00",
    },
    {
        "Student": "Muneeb Ali",
        "Gender": "Male",
        "Subject": "Physics",
        "Marks": 85,
        "Attendance_%": 93.0,
        "Exam_Date": "2025-03-14 11:30:00",
    },
    {
        "Student": "Iqra Malik",
        "Gender": "Female",
        "Subject": "Computer Science",
        "Marks": 80,
        "Attendance_%": 88.0,
        "Exam_Date": "2025-03-10 14:00:00",
    },
    {
        "Student": "Maryam Noor",
        "Gender": "Female",
        "Subject": "Physics",
        "Marks": 91,
        "Attendance_%": 95.5,
        "Exam_Date": "2025-03-14 11:30:00",
    },
    {
        "Student": "Abdullah Khan",
        "Gender": "Male",
        "Subject": "Computer Science",
        "Marks": 94,
        "Attendance_%": 97.0,
        "Exam_Date": "2025-03-10 14:00:00",
    },
    {
        "Student": "Talha Ahmed",
        "Gender": "Male",
        "Subject": "Mathematics",
        "Marks": 96,
        "Attendance_%": 99.0,
        "Exam_Date": "2025-03-12 09:00:00",
    },
    {
        "Student": "Laiba Fatima",
        "Gender": "Female",
        "Subject": "Physics",
        "Marks": 98,
        "Attendance_%": 98.0,
        "Exam_Date": "2025-03-14 11:30:00",
    },
    {
        "Student": "Mahnoor Ali",
        "Gender": "Female",
        "Subject": "Mathematics",
        "Marks": 99,
        "Attendance_%": 100.0,
        "Exam_Date": "2025-03-12 09:00:00",
    },
    {
        "Student": "Eman Raza",
        "Gender": "Female",
        "Subject": "Computer Science",
        "Marks": 100,
        "Attendance_%": 100.0,
        "Exam_Date": "2025-03-10 14:00:00",
    },
]
df = pd.DataFrame(data)
df.to_csv("student_performance.csv", index=False)
print("Created: student_performance.csv")
